version: "3.8"

services:
  example_nginx:
    image: nginx:latest
    container_name: example_nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 7777:80
  example_database:
    image: postgres:latest
    container_name: example_database
    ports:
      - 7776:5432
    volumes:
      - /docker/pgdata:/var/lib/postgresql/data
    environment:
      TZ: UTC
      POSTGRES_DB: ex_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JC5Ry3Sb

  example_php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: example_php-fpm
    volumes:
      # - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./laravelApp:/var/www/html
      # - ./docker/cron/cron.root:/etc/cron.d/cron
    working_dir: /var/www/html
    stdin_open: true
    tty: true